MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 4  # COCO is 80+1, DangerDet is 3+1
DATASETS:
  # TRAIN: ("coco_dangerdet_train", "coco_dangerdet_val")
  TRAIN: ("coco_dangerdet_train",)
  TEST: ("coco_dangerdet_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005  # 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (12000, 16000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 3500
  IMS_PER_BATCH: 18  # 16
  WARMUP_METHOD: "constant"
TEST:
  BBOX_AUG:
    ENABLED: False
    H_FLIP: True
    SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)  # mAP 0.942
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
